# Generated by Django 2.2.17 on 2021-01-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.IntegerField(blank=True, null=True, verbose_name='identifiant')),
                ('prenom', models.CharField(blank=True, max_length=200, null=True, verbose_name='Prénom')),
                ('nom', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom')),
                ('fonction', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fonctions/Grades')),
                ('tel', models.IntegerField(blank=True, null=True, verbose_name='Téléphone')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Email')),
            ],
        ),
    ]
